### ISSUE TITLE
ロゴの差し替え

### ISSUE THREAD

**Issue by tenntenn** [GoCon/2021-Spring#1]

**Comment by mi-bear** [comment]
とりあえず、作ってみました。まぁ、あとで差し替えも可能ですし！

![logo_text_black](https://user-images.githubusercontent.com/7250468/112741646-82740100-8fc2-11eb-83b5-5bd4aba89b78.png)
![logo_text](https://user-images.githubusercontent.com/7250468/112741648-84d65b00-8fc2-11eb-9b04-6642a2e69144.png)

**Comment by mi-bear** [comment]
ついでに、いくつかテキストを更新しました。

- Autumn -> Spring
- 2019 -> 2021

**Comment by tenntenn** [comment]
おしゃれ！

**Comment by quwen** [comment]
PaperCallの方はTokyoってついてますが、正式名称はどっちなのでしょうか？
https://www.papercall.io/gocon-tokyo-2021-spring

**Comment by tenntenn** [comment]
オフラインでは東京以外でもやってたのでtokyoとつけてた経緯があります。今回はオンラインなので東京とつけるとややこしくなるから外して良いと思います。

**Comment by quwen** [comment]
それもそうですね！ありがとうございます！
