### ISSUE TITLE
スタイルが崩れているところを直す

### ISSUE THREAD

**Issue by tenntenn** [GoCon/2021-Spring#13]

**Comment by syumai** [comment]
恐らくここ
<img width="1020" alt="スクリーンショット 2021-03-28 23 27 49" src="https://user-images.githubusercontent.com/6882878/112755827-68b3d780-901d-11eb-874c-6851ff31e6be.png">

**Comment by mi-bear** [comment]
syumai さんが対応してくれたので Close しちゃいます！
