### ISSUE TITLE
ハンズオンの内容と担当を決める

### ISSUE THREAD

**Issue by quwen** [GoCon/2021-Spring#21]
- Title: 数で遊ぼう 〜 コマンドラインツールで数を操る
- ディレクトリ: play-with-number
- スケジュール:
```
04/19 〜 04/23: 最終見直し
04/12 〜 04/18: codeelab でハンズオンページを作る (Google Doc)
       土台: @micchie
       校正: @mom0tomo
       上記の間にコードなどの修正とか見直し: @Miki
04/08 〜 04/11: コードレビュー @mom0tomo @micchie
04/01 〜 04/07: サンプルコードを作る @Miki
```

使いたいもの (つくるもの):
- flag パッケージ
- time パッケージ
- 数字に変換
-  (例) 素数判定
- メニューでなにか選ぶと、拡張できるように

**Comment by mi-bear** [comment]
やっていく内容と、スケジュール、タスクの割り振りが完了しているので完了とします。
