### ISSUE TITLE
スポンサーセッションの登録

### ISSUE THREAD

**Issue by mi-bear** [GoCon/2021-Spring#36]
Ref: https://goconjp.slack.com/archives/GPU5HCWE4/p1617367304310200
<img width="1192" alt="スポンサーセッションの登録" src="https://user-images.githubusercontent.com/7250468/113501344-40693300-955f-11eb-9692-682d7188e18e.png">

### (1) セッション名
スポンサー企業からセッション名をいただくので、それを表示します。
スピーカーたちのセッション名と同じような表示にしたいです。

### (2) 登壇者名
スポンサー企業から登壇者名をいただくので、それを表示します。
スピーカーたちの登壇者名と同じような表記 だが、顔写真ナシにしたいです。

### (3) 企業ロゴ
企業ロゴを表示したいです。

### (4) リンク先
スポンサーのページ (https://gocon.jp/partners/gold/xxx) に遷移したいです。

**Comment by syumai** [comment]
2019 Autumnの参考スクリーンショット
<img width="1146" alt="スクリーンショット 2021-04-04 14 45 31" src="https://user-images.githubusercontent.com/6882878/113499877-85d43300-9554-11eb-83e2-2a600f2f5396.png">

**Comment by syumai** [comment]
#42 でロゴは出すように出来た。
(1), (3), (4) は出来ているが、 (2) が出来ていない。
