### ISSUE TITLE
connpassの情報を登録

### ISSUE THREAD

**Issue by tenntenn** [GoCon/2021-Spring#5]

**Comment by mi-bear** [comment]
Miki さんが作業中
https://connpass.com/event/208896/edit/

**Comment by quwen** [comment]
- それぞれ定員数どうするか？
  - Youtube枠
    - 制限なし？
  - Youtube + 懇親会 (Remo) 枠
    -  運営、スポンサーを考慮してRemoのプランより人数を減らさないといけない
    - 先着順の場合、抽選日はいつ？

- アンケートは入れるか
  - 作成する場合、項目は？
  - 過去のものが利用できればそれを

**Comment by quwen** [comment]
ひとまずYoutube + 懇親会 (Remo) 枠を150人にしました。

**Comment by quwen** [comment]
一旦、確認待ち中です。

**Comment by quwen** [comment]
- Youtube枠
  - 制限なし
- Youtube + 懇親会 (Remo) 枠
  - 別のconnpassページを作成
  - Remoのプランが確定してから作成する
- ハンズオン枠
  - 作成する？
  - Remoで行う？

**Comment by mi-bear** [comment]
懇親会のものも作ってみました:
https://connpass.com/event/209271/edit/

**Comment by mi-bear** [comment]
チョット残作業があるけど、Opne にしたので、この Ticket は Close します。
