### ISSUE TITLE
gocon.jpからgocon.jp/2021springに移動する

### ISSUE THREAD

**Issue by vzvu3k6k** [GoCon/2021-Spring#77]
- [x] Hugoの生成物をサブディレクトリに対応させる
    - https://github.com/GoCon/2021-Spring/pull/76 をマージする
- [x] CIのデプロイ先をFirebaseからGitHub Pagesに変更する
    - https://github.com/GoCon/2021-Spring/pull/81 をマージする
- [x] リポジトリを2021springにリネームする（権限ある方お願いします）
    - GitHub PagesのURLのパスを`/2021spring`にするためです。大文字・小文字は区別されるので注意。
- [x] GitHub Pagesを有効にする（権限ある方お願いします）
    - 手順は[GitHubのドキュメント](https://docs.github.com/ja/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site)を参照してください。
    - github.com/gocon/gocon.github.ioのカスタムドメイン設定が自動的に引き継がれるので、2021-Springではカスタムドメインの設定は不要です。（UI上も設定不可になっているはず）
- [x] CircleCIを無効にする（ #81 でGitHub Actionsに移行するため不要になります。権限ある方お願いします）
- 完了！

**Comment by syumai** [comment]
↑こちら対応しました！ありがとうございます！
https://gocon.jp/2021spring/
問題無さそうです

**Comment by syumai** [comment]
こちらCloseします
